.Dd 26 April 2001
.TH SECS 6
.SH NAME
.Nm secs
.Nd Spouts Erotic Crazy Stories
.Sh SYNOPSIS
.Nm secs
.Op None
.Sh DESCRIPTION
.Nm secs
Spouts erotic, crazy, one-line stories in a madlib style.
.Sh AUTHOR
.An Unknown.  Adopted and cleaned up by Nick Johnson <freebsd@spatula.net>. Further polished (forked) by Jan "Paal" Brennen <jan@janpaal.com>
